name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm run build && npm run package

  test: # make sure the action works on a clean machine without building
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir test.app
      - uses: ./
        with:
          name: test
          srcdir: ./test.app
      - uses: actions/upload-artifact@v4.6.1
        with:
          name: test
          path: |
            ./test.dmg
      - run: |
          sudo hdiutil attach ./test.dmg
